### PR TITLE
M1 Mac compatibility

### PR DESCRIPTION
**Pull request by thinkyhead**
Add Arm64 builds of both bAtari-Basic and `dasm`, plus a link to the x86 build of Stella — until a Universal build is available.

### CODE REVIEW

**Comment by chunkypixel** [comment]
Hi @thinkyhead - apologies for not getting to this yet (i'd forgetten TBH and have been flatout with real life).  This actually just popped up as an issue on AtariAge (https://atariage.com/forums/topic/333127-ataribasic-will-it-run-on-the-m1-mac) so you may be prvented this if i'd done something about it 😢 It will require me to determine how to identify M1 within Typecode so I can launch the appropriate compiler files so will need to investigate very soon.

**Comment by thinkyhead** [comment]
> It will require me to determine how to identify M1 within Typescript

If you query the system, the OS will be identified as "darwin" and the architecture will be "arm64."

**Comment by thinkyhead** [comment]
Even better than the Javascript version of DASM (or as a good companion) there is also a Javascript Atari 2600 emulator at https://github.com/ppeccin/javatari.js which could be embedded inside the extension, removing the need for Stella or another emulator to be installed on the user computer, and the game could run right inside the WebView, with full access to the running state.

**Comment by chunkypixel** [comment]
Thanks @thinkyhead for the ARM versions!

**Pull request merged**
